[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"


[[edge_functions]]
function = "redirect"
path = "/products/ace-calibration-management-system-on-cloud"

[[edge_functions]]
function = "redirect"
path = "/products/ace-calibration-management-system-on-cloud/*"


[[edge_functions]]
function = "redirect"
path = "/products/ace-project-management-software"

[[edge_functions]]
function = "redirect"
path = "/products/ace-project-management-software/*"